kind: Service
apiVersion: v1
metadata:
  name: ping-exporter
  namespace: {{ .Values.namespace }}
  labels:
    app: ping-exporter
spec:
  clusterIP: None
  selector:
    app: ping-exporter
  ports:
    - name: web
      port: 8080
